# Generated by Django 5.2.4 on 2025-07-10 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questin',
            new_name='Question',
        ),
    ]
